In [1]:
import sys
import os
import pandas as pd

In [2]:
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..', 'src')))

In [3]:
from data.load_data import load_data
from data.make_dataset import FraudFeatureEngineer

In [4]:
df_raw = load_data("../data/raw/dados.csv")
print("Raw data shape:", df_raw.shape)
display(df_raw.head())

Raw data shape: (150000, 20)

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,fecha,monto,score,fraude
0,4,0.7685,94436.24,20.0,0.444828,1.0,BR,5,Máquininha Corta Barba Cabelo Peito Perna Pelo...,cat_8d714cd,0.883598,240.0,102.0,1,NaN,N,2020-03-27 11:51:16,5.64,66,0
1,4,0.7550,9258.50,1.0,0.000000,33.0,BR,0,Avental Descartavel Manga Longa - 50 Un. Tnt ...,cat_64b574b,0.376019,4008.0,0.0,1,Y,N,2020-04-15 19:58:08,124.71,72,0
2,4,0.7455,242549.09,3.0,0.000000,19.0,AR,23,Bicicleta Mountain Fire Bird Rodado 29 Alumini...,cat_e9110c5,0.516368,1779.0,77.0,1,NaN,N,2020-03-25 18:13:38,339.32,95,0
3,4,0.7631,18923.90,50.0,0.482385,18.0,BR,23,Caneta Delineador Carimbo Olho Gatinho Longo 2...,cat_d06e653,0.154036,1704.0,1147.0,1,NaN,Y,2020-04-16 16:03:10,3.54,2,0
4,2,0.7315,5728.68,15.0,0.000000,1.0,BR,2,Resident Evil Operation Raccoon City Ps3,cat_6c4cfdc,0.855798,1025.0,150.0,1,NaN,N,2020-04-02 10:24:45,3.53,76,0

In [5]:
engineer = FraudFeatureEngineer()
df_engineered = engineer.transform(df_raw)
print("Engineered data shape:", df_engineered.shape)
display(df_engineered.head())

Engineered data shape: (150000, 45)

,a,b,c,d,e,f,g,h,i,j,...,i_num_count_agrup,i_cleaned,i_word_original,i_word_kit,i_word_gb,i_word_ram,j_cluster,j_cluster_agrup,k_bin,o_transformed
0,4,0.7685,94436.24,20.0,0.444828,1.0,BR,5,Máquininha Corta Barba Cabelo Peito Perna Pelo...,cat_8d714cd,...,0,maquininha corta barba cabelo peito perna pelo...,0,0,0,0,1,0,3,2
1,4,0.7550,9258.50,1.0,0.000000,33.0,BR,0,Avental Descartavel Manga Longa - 50 Un. Tnt ...,cat_64b574b,...,0,avental descartavel manga longa 50 un tnt ho...,0,0,0,0,7,0,1,1
2,4,0.7455,242549.09,3.0,0.000000,19.0,AR,23,Bicicleta Mountain Fire Bird Rodado 29 Alumini...,cat_e9110c5,...,0,bicicleta mountain fire bird rodado 29 alumini...,0,0,0,0,6,0,2,2
3,4,0.7631,18923.90,50.0,0.482385,18.0,BR,23,Caneta Delineador Carimbo Olho Gatinho Longo 2...,cat_d06e653,...,0,caneta delineador carimbo olho gatinho longo 2...,0,0,0,0,8,0,0,2
4,2,0.7315,5728.68,15.0,0.000000,1.0,BR,2,Resident Evil Operation Raccoon City Ps3,cat_6c4cfdc,...,0,resident evil operation raccoon city ps3,0,0,0,0,1,0,3,2

In [6]:
output_path = "../data/processed/processed_data.csv"
df_engineered.to_csv(output_path, index=False)
print(f"Engineered dataset saved to {output_path}")

Engineered dataset saved to ../data/processed/processed_data.csv